### ISSUE TITLE
How to make astra-toolbox compatible with tensorflow-gpu

### ISSUE THREAD

**Issue by ginsanity15** [adler-j/learned_gradient_tomography#2]
Hey Jonas,

I was trying to run code: "Partially_learned_gradient_descent.py" in this repository but I have encountered a dilemma as follow. 

In order to utilize GPU for the computation of forward and backward projection in ODL, it is mandatory for us to install "Astra-toolbox". However, installing "Astra-toolbox" will downgrade package "numpy" to version 1.12. If we import tensorflow (version 1.13.1) to python in this situation, the following error message will occur:

> ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
> ImportError: numpy.core.multiarray failed to import
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 968, in _find_and_load
> SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
> ImportError: numpy.core._multiarray_umath failed to import
> ImportError: numpy.core.umath failed to import

I have tried to upgrade "numpy" (for instance, to version 1.16) after installing "astra-toolbox", but then ODL will complain there is no available back-end for Ray-Transform. 

Have you met this problem before? If so, could you please tell me how could I solve it? Thanks for your attention, I am looking forward to hear back from you.

Cheers,
Bo

**Comment by adler-j** [comment]
If someone finds this, the solution is here: https://github.com/odlgroup/odl/issues/1482
